### ISSUE TITLE
ValueError: cannot convert float NaN to integer during Predict sometimes at runtime

### ISSUE THREAD

**Issue by aseembehl** [jeasinema/VoxelNet-tensorflow#27]
Also mentioned in the closed issue here:
https://github.com/jeasinema/VoxelNet-tensorflow/issues/13

predict ['007029' '006278' '007221' '005063']
~/tensorflow/lib/python3.5/site-packages/numpy/core/_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    tf.app.run(main)
  File "~/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 118, in main
    sess, valid_loader.load(), summary=True)
  File "~/Work/VoxelNet-tensorflow/model/model.py", line 320, in predict_step
    batch_gt_boxes3d[0])
  File "~/Work/VoxelNet-tensorflow/utils/utils.py", line 339, in draw_lidar_box3d_on_image
    projections = lidar_box3d_to_camera_box(boxes3d, cal_projection=True)
  File "~/Work/VoxelNet-tensorflow/utils/utils.py", line 298, in lidar_box3d_to_camera_box
    minx = int(np.min(points[:, 0]))
ValueError: cannot convert float NaN to integer

**Comment by ezeddin** [comment]
Hi!
I have the same problem, do you have solve it?

**Comment by aseembehl** [comment]
Sorry, I don't have a proper solution for this. But the problem seems to be in the summary part where the predicted bounding boxes are converted to camera coordinates for plotting on images.

**Comment by mariabency** [comment]
Hi!
I have the same problem, have you solved it?

**Comment by mariabency** [comment]
Hi!
I have the same problem, have you solved it?
