### ISSUE TITLE
test.py error

### ISSUE THREAD

**Issue by herry0401** [jeasinema/VoxelNet-tensorflow#42]
hello, I am already done my training work but when I did python3 test.py, there comes an error:

Dataset total length: 0
2018-05-11 17:25:13.173997: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/VoxelNet-tensorflow/utils/kitti_loader.py", line 233, in loader_worker_main
    self.fill_queue(batch_size)
  File "/home/user/VoxelNet-tensorflow/utils/kitti_loader.py", line 162, in fill_queue
    voxel[idx * single_batch_size:(idx + 1) * single_batch_size])
  File "/home/user/VoxelNet-tensorflow/utils/kitti_loader.py", line 265, in build_input
    feature = np.concatenate(feature_list)
ValueError: need at least one array to concatenate
2018-05-11 17:25:13.256266: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-05-11 17:25:13.256663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: TITAN Xp COLLECTORS EDITION major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 11.91GiB freeMemory: 10.23GiB
2018-05-11 17:25:13.256680: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-05-11 17:25:13.434146: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-05-11 17:25:13.434184: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-05-11 17:25:13.434190: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-05-11 17:25:13.434382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 12194 MB memory) -> physical GPU (device: 0, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:01:00.0, compute capability: 6.1)
WARNING:tensorflow:From /home/user/VoxelNet-tensorflow/model/group_pointcloud.py:75: calling reduce_max (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Reading model parameters from ./save_model/default
test done.

There is no output coming from testing.
My dataset directory is same in data/object/training(testing)/image_2  label_2  velodyne.
Can you help me solve the problem? Thank you a lot!

**Comment by woganda** [comment]
did you solve it? i meet the same problem.

**Comment by lesterlo** [comment]
I have the same problem. How to solve it?
